# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: requirements-txt-fixer
    - id: double-quote-string-fixer
    - id: check-merge-conflict
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: mixed-line-ending
      args: ["--fix=lf"]
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
- repo: https://github.com/PyCQA/isort
  rev: 5.11.5
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
  - id: codespell
